steps:
  - label: ":pipeline: Launch Pipelines"
    command: buildkite-agent pipeline upload .buildkite/runtests.yml
    agents:
      queue: "juliaecosystem"
      sandbox.jl: true

  - label: ":pipeline: Launch Downstream Documentation Builds"
    command: buildkite-agent pipeline upload .buildkite/docs_downstream.yml
    agents:
      queue: "juliaecosystem"
      sandbox.jl: true
